project:
  type: website

website:
  title: "Mid-Atlantic Rugby Referees"
  navbar:
    background: success 
    foreground: dark
    left:
      - about.qmd
      - text: Reimbursement Form
        href: https://docs.google.com/forms/d/1gaqwOQ4LWzOPcFlu7MspXD7Ir5_VWiiSfiUvytvfjcM/edit
      - text: Discipline Reporting
        href: discipline/index.qmd

format:
  html:
    theme: litera
    css: styles.css
    toc: true

execute: 
  freeze: auto

