---
title: "Discipline"
---

## Protocol

If you have a red card:

1.    Notify the MARR president (Mike O'Brien: [mikeob9@gmail.com](mailto:mikeob9@gmail.com)) and the Eastern Regional Disciplinary Representative (Bryan Dewease: [bdewease@gmail.com](mailto:bdewease@gmail.com));
2.    **DO NOT** review film -- we do not want to referee after the match;
3.    Complete the disciplinary report below.

All cards should be reported to the Geographic Union that is hosting the match. So, for example:

-   NOVA plays Schuylkill at Schuylkill: All cards to either side are reported to the Eastern Pennsylvania Rugby Union.
-   NOVA plays Schuylkill at NOVA: All cards to either side are reported to the Capital Rugby Union.

## Eastern Pennsylvania Rugby Union (EPRU)

[Report all incidents in an EPRU-hosted match here.](http://epru.rugby/referee-disciplinary-report/)

ERPU-hosted matches are those at Philadelphia Women and Schuylkill River.

## Capital Rugby Union (CRU)

[Report all incidents in a CRU-hosted here.](https://form.jotform.us/70856323467159)

CRU-hosted matches are all those *not* hosted by Philadelphia Women or Schuylkill River.

